services:
  green:
    container_name: green
    image: green
    build:
      context: ../..
      dockerfile: ./zero-downtime-deployment-v1/docker/Dockerfile
    environment:
      - ACTIVE_PROFILE=green
    ports:
      - 8080:8080
#    expose:
#      - 8080