services:
  blue:
    container_name: blue
    image: blue
    build:
      context: ../..
      dockerfile: ./zero-downtime-deployment-v1/docker/Dockerfile
    environment:
      - ACTIVE_PROFILE=blue
    ports:
      - 8081:8080
#    expose:
#      - 8081