services:
  nginx:
    image: nginx:1.21.5-alpine
    ports:
      - 80:80
    volumes:
      - ../proxy/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./work.html:/usr/share/nginx/html/work.html
    container_name: nginx-proxy
    networks:
      - blue-network
      - green-network

networks:
  blue-network:
    external: true
  green-network:
    external: true